### ISSUE TITLE
Bad Request - ERROR 3840: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by buskerone** [AzureAD/azure-activedirectory-library-for-objc#537]
I'm able to Sign Up but when I try to Sign In I get this error: 

environment: iOS 9.1, Xcode 7.1.1, branch 'convergence-dev' (B2C)

> 2016-02-24 17:48:30.047 Microsoft Tasks for Consumers[8167:232019] -[ADAuthenticationBroker webAuthenticationDidCompleteWithURL:][408][main] 
2016-02-24 17:48:31.275 Microsoft Tasks for Consumers[8167:232077] ADALiOS [2016-02-24 20:48:31 - 00000000-0000-0000-0000-000000000000] ERROR: JSON deserialization. Additional Information: Error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}. Body text: 'Bad Request'. HTTPS Code: 400. Response correlation id: (null). ErrorCode: 3840.
2016-02-24 17:48:31.287 Microsoft Tasks for Consumers[8167:232077] ADALiOS [2016-02-24 20:48:31 - 00000000-0000-0000-0000-000000000000] ERROR: Error raised: 3840. Additional Information: Domain: NSCocoaErrorDomain Details: The data couldn’t be read because it isn’t in the correct format.. ErrorCode: 3840.

<img width="763" alt="captura de pantalla 2016-02-24 a las 17 50 17" src="https://cloud.githubusercontent.com/assets/2034112/13300678/12ba650e-db20-11e5-8609-0e749b51f85a.png">

It's returning a Bad Request and I'm waiting for a JSON... Any clue?

**Comment by martinpgrayson** [comment]
I am getting the very same issue, using 3.0.0-pre3.

**Comment by buskerone** [comment]
It's a known issue I think.

I've reported this 1 week ago in the B2C-NativeClient-iOS. It seems to be a bug that is resolved in another branch (that's what a Microsoft developer said to me) but he never said to me in what branch is fixed.

 Hope anyone can give us an answer here.

**Comment by martinpgrayson** [comment]
Ah great. I replicated the question over in Stack Overflow too:

http://stackoverflow.com/questions/35704726/bad-request-error-3840-the-data-couldn-t-be-read-because-it-isn-t-in-the-corr

I will check out the post in the sample repo. I am not using the sample, but still see the same error, so assuming the fix was not in the sample, but in ADALiOS.

**Comment by jasoncoolmax** [comment]
@buskerone @martinpgrayson Could you please confirm that this still happens with the latest convergence-dev branch? if so, could you provide the logs such that I can look into details?

To get full logs of ADAL, you need to set the log level. 
I.e., assuming you are using the B2C-NativeClient-iOS demo in Github, put [ADLogger setLevel:ADAL_LOG_LEVEL_VERBOSE]; somewhere before you make the request, say put it in the beginning of method [samplesWebAPIConnector getClaimsWithPolicyClearingCache:].

PS: you may need to import the header file as well #import "ADALiOS/ADLogger.h".

**Comment by jasoncoolmax** [comment]
@buskerone @martinpgrayson 
I have somehow managed to reproduce the issue. 

The reason is: your client ID set in the *scope* value and your client ID are not the same (look at those values you provided to function *acquireTokenWithScopes*)

Solution: set them the same.

Please do let me know if the above solves the problem, such that I can close the issue :)

**Comment by buskerone** [comment]
Sorry but it has been a long time since I reported this error and nobody gave me a good answer. I even communicated with a Microsoft developer and he didn't give me more answers. Because it was an urgent ticket to solve, my solution was to move to another lib (simple OAuth2.0 lib for iOS). ADALiOS is just another Oauth 2.0 lib but with a lot of issues. I think that the problem was because the request was made twice in your lib so you get a Bad Request message. Don't have the code right now so I can't reproduce the error, but I'm sure that was the problem. You can close this if you want but the problem will persist. Maybe @martinpgrayson could give as a feedback.
Hope that you understand.

**Comment by jasoncoolmax** [comment]
@buskerone I am sorry to hear that you didn't get enough technical support :P

For the issue itself, I have followed your description and things work fine, unless I mess up a bit with the configuration (providing different client ID as I mentioned above), then I got exactly the same error you had. 

If you have any clue that the error could happen in other cases, you are very welcome to provide more information, which will definitely help us make ADAL better :)

**Comment by martinpgrayson** [comment]
Hi @jasoncoolmax 

Similar to @buskerone , I ended up writing my own browser auth control, and calls to refresh the token. 

I would be happy to revisit this in our next rev, however, so appreciate your attention.

Martin
